### ISSUE TITLE
Push Notifications for Comments Click Behaviour

### ISSUE THREAD

**Issue by kharoof** [eSteemApp/esteem#52]
When you get a push notification or popup message to your phone for comments it would be a nice enhancement if when you clicked on it the app opened at the comment. 

At the moment nothing happens when you click the push notification and nothing happens when you click the popup message.

**Comment by feruzm** [comment]
It was working until recently. I will take a look, expected behavior would be, when you tap on notification (comment, follow, reblog) it would open app and show confirmation dialog to take you to that post or profile. Something might be broken if above behavior is not working. thank you for reporting!

**Comment by kharoof** [comment]
As you said is what I was thinking exactly for the expected behaviour.

**Comment by feruzm** [comment]
v1.3.9 should address this issue. Although improvements will be made to handle chain changes. If you open notification from Golos but chain is set to Steem you might have issues.
